from django.urls import path
from multiplataforma import settings
from . import views
from django.conf.urls.static import static
from .views import cargar_shapefile
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.inicio_2, name='inicio_2'),
    path('load-municipios/', views.load_municipios, name='load_municipios'),
    path('load-cv/', views.load_cv, name='load_cv'),
    path('cargar_cv/', views.cargar_cv, name='cargar_cv'),
    path('cargar_cme/', views.cargar_cme, name='cargar_cme'),
    path('cargar_guia_tel/', views.cargar_contactos, name='cargar_guia'),
    path('cargar-shapefile/', cargar_shapefile, name='cargar_shapefile'),
    path('cv', views.frm_princ_cv , name='cv'),
    path('admin_cv', views.frm_adminxunidad_cv , name='admin_cv'),
    path('mapa', views.frm_mapa , name='mapa'),
    path('guia', views.guia_tel , name='guia_tel'),
    path('guia_cv', views.guia_tel_cv , name='guia_cv'),
    path('rpt_info_gen', views.rpt_info_gen , name='rpt_info_gen'),
    path('rpt_info_situacion', views.rpt_info_situacion , name='rpt_info_situacion'),
    path('registrar/', views.registrar_manual, name='registrar_manual'),
    path('actualizar_cv/', views.actualizar_cv, name='actualizar_cv'),
    path('centro/actualizar_estado/', views.actualizar_estado_cv, name='actualizar_estado'),
    path('centro/detalle/<int:centro_id>/', views.detalle_centro, name='centro_detalle'),
    path('obtener_datos_cv/', views.obtener_datos_cv, name='obtener_datos_cv'),
    path('eliminar_contacto/', views.eliminar_contacto, name='eliminar_contacto'),
    path('mapa1/', views.mapa_municipios, name='mapa_municipios'),
    path('municipios.geojson', views.geojson_municipios, name='geojson_municipios'),
    path('depto.geojson', views.geojson_depto, name='geojson_depto'),
    path('rpt_info_depto/', views.mapa_departamento, name='rpt_info_depto'),
    path('geojson/<str:departamento>/', views.geojson_departamento, name='geojson_departamento'),
    path('centros/<str:id_departamento>/', views.centros_por_departamento, name='centros_por_departamento'),
    path("centros_municipio/<str:cod_municipio>/", views.centros_por_municipio, name="centros_por_municipio"),
    path('centro/<int:centro_id>/personal/', views.obtener_personal_cv, name='obtener_personal_cv'),
    path('centro/agregar_personal/', views.agregar_personal_cv, name='agregar_personal_cv'),
    path('centro/eliminar_personal/<int:id>/', views.eliminar_personal, name='eliminar_personal'),
    path('centro/<int:centro_id>/foto/', views.obtener_foto_cv),
    path('centro/guardar_foto/', views.guardar_foto_cv),
    path('centro/guardar_ubicacion/', views.guardar_ubicacion_cv, name='guardar_ubicacion_cv'),
    path('detalle-departamento/<int:codigo>/', views.detalle_departamento, name='detalle_departamento'),
    path('admin_cde', views.frm_admin_cde , name='admin_cde'),
    path('registrar-cde/', views.registrar_cde, name='registrar_cde'),
    path('eliminar_cde/<int:pk>/', views.eliminar_cde, name='eliminar_cde'),
    path('cde/obtener/<int:id>/', views.obtener_cde, name='obtener_cde'),
    path('cde/<int:cde_id>/foto/', views.obtener_foto_cde),
    path('cde/guardar_foto/', views.guardar_foto_cde),
    path('cde/guardar_ubicacion/', views.guardar_ubicacion_cde, name='guardar_ubicacion_cde'),
    path('cde/<int:centro_id>/personal/', views.obtener_personal_cde, name='obtener_personal_cde'),
    path('cde/agregar_personal/', views.agregar_personal_cde, name='agregar_personal_cde'),
    path('cde/<int:centro_id>/foto/', views.obtener_foto_cde),
    path('cde/actualizar_estado/', views.actualizar_estado_cde, name='actualizar_estado_cde'),
    path('exportar-cde/', views.exportar_cde_excel, name='exportar_cde_excel'),
    path('admin_cme', views.frm_admin_cme , name='admin_cme'),
    path('registrar-cme/', views.registrar_cme, name='registrar_cme'),
    path('eliminar_cme/<int:pk>/', views.eliminar_cme, name='eliminar_cme'),
    path('cme/obtener/<int:id>/', views.obtener_cme, name='obtener_cme'),
    path('cme/<int:cme_id>/foto/', views.obtener_foto_cme),
    path('cme/guardar_foto/', views.guardar_foto_cme),
    path('cme/guardar_ubicacion/', views.guardar_ubicacion_cme, name='guardar_ubicacion_cme'),
    path('cme/<int:centro_id>/personal/', views.obtener_personal_cme, name='obtener_personal_cme'),
    path('cme/agregar_personal/', views.agregar_personal_cme, name='agregar_personal_cme'),
    path('cme/<int:centro_id>/foto/', views.obtener_foto_cme),
    path('cme/actualizar_estado/', views.actualizar_estado_cme, name='actualizar_estado_cme'),
    path('exportar-cme/', views.exportar_cme_excel, name='exportar_cme_excel'),
    path('exportar-cve/', views.exportar_cve_excel, name='exportar_cve_excel'),
    path('logout/', views.cerrar_sesion, name='cerrar_sesion'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
]
