# Generated by Django 5.0.2 on 2025-05-14 22:18

import django.db.models.deletion
import modulos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True, unique=True)),
                ('depto', models.CharField(max_length=100)),
                ('munic', models.CharField(max_length=100)),
                ('cv', models.CharField(max_length=100)),
                ('grado1', models.CharField(max_length=100)),
                ('nom1', models.CharField(max_length=100)),
                ('num1', models.CharField(max_length=100)),
                ('grado2', models.CharField(max_length=100)),
                ('nom2', models.CharField(max_length=100)),
                ('num2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='contactoxcv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('num', models.CharField(max_length=100)),
                ('img', models.FileField(blank=True, null=True, upload_to=modulos.models.camb_nom_arch)),
            ],
        ),
        migrations.CreateModel(
            name='depto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='munic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cod_munic', models.TextField(null=True)),
                ('descrip_corta', models.TextField()),
                ('cod_depto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='modulos.depto')),
            ],
        ),
        migrations.CreateModel(
            name='procedencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
                ('descrip_larga', models.TextField()),
                ('cod_proced_superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='modulos.procedencia')),
            ],
        ),
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longitud', models.FloatField(null=True)),
                ('latitud', models.FloatField(null=True)),
                ('sector_electoral', models.TextField(blank=True, null=True)),
                ('carga_electoral', models.TextField(null=True)),
                ('nom', models.TextField(blank=True, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to=modulos.models.camb_nom_arch)),
                ('cod_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.area')),
                ('cod_depto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.depto')),
                ('cod_estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.estado')),
                ('cod_munic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.munic')),
                ('procedencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.procedencia')),
            ],
        ),
    ]
