# Generated by Django 5.0.2 on 2025-05-22 21:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0002_contactoxcv_cod_cv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Munic_Geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('shapeid', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('cod_munic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.munic')),
            ],
        ),
    ]
