# Generated by Django 5.0.2 on 2025-05-23 01:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0003_munic_geo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='munic_geo',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
