# Generated by Django 5.0.2 on 2025-05-23 01:08

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0004_alter_munic_geo_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='munic_geo',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
        ),
    ]
