# Generated by Django 5.0.2 on 2025-05-25 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0005_alter_munic_geo_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='munic_geo',
            name='cod_depto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.depto'),
        ),
    ]
