# Generated by Django 5.0.2 on 2025-06-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0007_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guia_Telefonica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True, unique=True)),
                ('grado', models.CharField(max_length=100)),
                ('nom_ape', models.CharField(max_length=100)),
                ('fuerza', models.CharField(max_length=100)),
                ('unidad', models.CharField(max_length=100)),
                ('cargo_actual', models.CharField(max_length=100)),
                ('tel_oficina', models.CharField(max_length=100)),
                ('tel_ip', models.CharField(max_length=100)),
                ('tel_celular', models.CharField(max_length=100)),
                ('correo_inst', models.CharField(max_length=100)),
                ('correo_personal', models.CharField(max_length=100)),
            ],
        ),
    ]
