# Generated by Django 5.0.2 on 2025-07-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0008_guia_telefonica'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='jrv',
            field=models.TextField(null=True),
        ),
    ]
