# Generated by Django 5.0.2 on 2025-07-21 17:10

import django.db.models.deletion
import modulos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0009_cv_jrv'),
    ]

    operations = [
        migrations.CreateModel(
            name='cde',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('obs', models.TextField(blank=True, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to=modulos.models.camb_nom_arch)),
                ('longitud', models.FloatField(null=True)),
                ('latitud', models.FloatField(null=True)),
                ('hora_desp_salida', models.DateTimeField(null=True)),
                ('hora_desp_llegada', models.DateTimeField(null=True)),
                ('hora_redesp_salida', models.DateTimeField(null=True)),
                ('hora_redesp_llegada', models.DateTimeField(null=True)),
                ('cod_depto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.depto')),
                ('cod_estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.estado')),
                ('cod_munic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.munic')),
                ('procedencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.procedencia')),
            ],
        ),
        migrations.AddField(
            model_name='contactoxcv',
            name='cod_cde',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.cde'),
        ),
    ]
