# Generated by Django 5.0.2 on 2025-08-04 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0010_cde_contactoxcv_cod_cde'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado_cde',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cde',
            name='cod_estado',
        ),
        migrations.AddField(
            model_name='cde',
            name='cod_estado_cde',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.estado_cde'),
        ),
    ]
