# Generated by Django 5.0.2 on 2025-08-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0011_estado_cde_remove_cde_cod_estado_cde_cod_estado_cde'),
    ]

    operations = [
        migrations.AddField(
            model_name='cde',
            name='carga_electoral',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
