# Generated by Django 5.0.2 on 2025-08-06 15:03

import django.db.models.deletion
import modulos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0013_depto_geo'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado_cme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='cme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.FileField(blank=True, null=True, upload_to=modulos.models.camb_nom_arch)),
                ('longitud', models.FloatField(null=True)),
                ('latitud', models.FloatField(null=True)),
                ('hora_desp_salida', models.DateTimeField(null=True)),
                ('hora_desp_llegada', models.DateTimeField(null=True)),
                ('hora_redesp_salida', models.DateTimeField(null=True)),
                ('hora_redesp_llegada', models.DateTimeField(null=True)),
                ('carga_electoral', models.IntegerField(blank=True, null=True)),
                ('cod_depto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.depto')),
                ('cod_estado_cme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.estado_cde')),
                ('cod_munic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.munic')),
                ('procedencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.procedencia')),
            ],
        ),
    ]
