# Generated by Django 5.0.2 on 2025-08-06 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0014_estado_cme_cme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cme',
            name='cod_estado_cme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.estado_cme'),
        ),
    ]
