# Generated by Django 5.0.2 on 2025-08-06 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulos', '0015_alter_cme_cod_estado_cme'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoxcv',
            name='cod_cme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modulos.cme'),
        ),
    ]
